### ISSUE TITLE
Newsletter suscribe button

### ISSUE THREAD

**Issue by akanksha-raghav** [StudentCode-in/StudentCode-in.github.io#101]
When anyone subscribes to the newsletter after clicking the subscribe button the email id remains there, it should be removed as a fresh blank

**Comment by V3dant** [comment]
Hey @akanksha-raghav can I work on this issue?

**Comment by akanksha-raghav** [comment]
Sure @V3dant, Please go-ahead

**Comment by V3dant** [comment]
Hey @akanksha-raghav please look into my pull request. You wanted to empty the placeholder but instead of that on clicking submit button it will show Thank you for subscribing to our newsletters. Let me know if you want the empty field instead of that.
