### ISSUE TITLE
Please invite me to the GitHub Community Organisation 

### ISSUE THREAD

**Issue by JayantGoel001** [StudentCode-in/StudentCode-in.github.io#109]
I would like to join This Organization.

**Comment by lakshyatyagi24** [comment]
@itsallarchit and @akanksha-raghav please handle this issue

**Comment by akanksha-raghav** [comment]
Hey, @JayantGoel001 the participants of the SCI program are only invited to the organization stay tuned for getting info on further programs with our LinkedIn page:
https://www.linkedin.com/company/43204229/admin/
