### ISSUE TITLE
Need improvement in Preloader

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#127]
Preloader need to be more smother

**Comment by chinmaym07** [comment]
Hey @lakshyatyagi24  I have tried this.
Please have a look at the below gif . It is smooth .
Shall I open a pr for the same .?

![Peek 2020-12-09 19-18](https://user-images.githubusercontent.com/44670961/101637982-7b48d780-3a53-11eb-9831-1aa09fbf4894.gif)

**Comment by lakshyatyagi24** [comment]
Yes please open a new PR

**Comment by saumyasrivastava08** [comment]
I have fixed this issue and created a PR as I was getting errors during pushing it using gitbash like fatal error remote access, I tried a lot to fix but I couldn't.
Therefore I have created a PR manually.
Please look and merge it

**Comment by lakshyatyagi24** [comment]
@akanksha-raghav please look into it

**Comment by akanksha-raghav** [comment]
@saumyasrivastava08 you have opened a PR and reverted it back please create an another one.

**Comment by saumyasrivastava08** [comment]
I am facing a lot issue while pushing it using git bash. I will create pr but manually. 
I don't know why this issue is coming while pushing it using git bash

**Comment by lakshyatyagi24** [comment]
Please try to create PR directly on github.

**Comment by saumyasrivastava08** [comment]
I have created the PR and github is more smoother
