### ISSUE TITLE
Active Screen Overlay on Fixed Header

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#129]
![image](https://user-images.githubusercontent.com/48288540/101186339-f6d40e80-3678-11eb-9d19-38112dd98f16.png)

**Comment by Vineet955** [comment]
Hello @lakshyatyagi24 , Can i work on this issue?

**Comment by lakshyatyagi24** [comment]
sure @Vineet955

**Comment by saumyasrivastava08** [comment]
I want to contribute to open source Projects .Can I work on this issue

**Comment by chinmaym07** [comment]
Hey @lakshyatyagi24 can I try this. ?

**Comment by akanksha-raghav** [comment]
yes sure @saumyasrivastava08 and @chinmaym07

**Comment by saumyasrivastava08** [comment]
is this issue still open i am working on it

**Comment by lakshyatyagi24** [comment]
Yes @saumyasrivastava08
