### ISSUE TITLE
Interested to Participate 

### ISSUE THREAD

**Issue by akrish4** [StudentCode-in/StudentCode-in.github.io#139]
I would like to be part of this  community and would like to contribute , kindly let me know 
Am I able to register now ? If not when can i register to be a part of this open source program and 
Kindly let me know all the future SCI open source programs ?

**Comment by lakshyatyagi24** [comment]
You can Participate in SCI2020. @akanksha-raghav will share you more details.

**Comment by akrish4** [comment]
Okay thank you @lakshyatyagi24  , SCI2020 how to register ? any registration needed @akanksha-raghav  ?

**Comment by akanksha-raghav** [comment]
Hey, @akrish4 thank you for showing your interest in SCI. SCI-2020 registrations are closed.
For further programs and sessions stay tuned with: https://www.linkedin.com/company/43204229/admin/
