### ISSUE TITLE
Logo of Organization is not visible on User's GitHub Profile

### ISSUE THREAD

**Issue by lelouchB** [StudentCode-in/StudentCode-in.github.io#2]
**Is your feature request related to a problem? Please describe.**
Student Code In logo is not visible on the GitHub profile of Organization Members.
![image](https://user-images.githubusercontent.com/45850882/83344893-914e4080-a32a-11ea-9ea5-f2422aec4eac.png)

**Describe the solution you'd like**
Change the logo to something visible.

**Comment by Anisha1234** [comment]
@lelouchB @akanksha-raghav just increasing the size of the logo might help.

**Comment by akanksha-raghav** [comment]
Logo Updated
