### ISSUE TITLE
[Project Missing] Water Monitoring System Project is not listed on the website

### ISSUE THREAD

**Issue by vinitshahdeo** [StudentCode-in/StudentCode-in.github.io#21]
Hello,

I'm not able to see [Water Monitoring System](https://vinitshahdeo.github.io/Water-Monitoring-System/) on the [Projects](https://scodein.tech/project.html) page. Seems like **it's not listed on the website**: [scodein.tech](https://scodein.tech/)!

Here's the [link](https://github.com/vinitshahdeo/Water-Monitoring-System) to the GitHub repo.

**PS: If you wish, I can raise the PR for the same.**

With optimism,
**[Vinit Shahdeo](https://www.linkedin.com/in/vinitshahdeo/)**
<sup>**Project Admin**</sup>

**Comment by cipheraxat** [comment]
Hey @vinitshahdeo , 
We didn't found your submission of project in the form which was provided when we rolled out the selection form
We are not going to entertain any request which doesn't follow any rules. As it was clearly mentioned filling the form was mandatory.
I also had a chat with @PragatiVerma18 . You can refer her.
With regards
SCI team

**Comment by vinitshahdeo** [comment]
@cipheraxat Thanks for informing.

Closing this issue.
Good luck!
