### ISSUE TITLE
Student code-in in the projects page

### ISSUE THREAD

**Issue by abhinavsri360** [StudentCode-in/StudentCode-in.github.io#27]
**Describe the bug**
On the projects page the heading i.e., 'STUDENT CODE-IN' should redirect to the home page of the website i.e., scodein.tech which not doing as expected.

**To Reproduce**
can add a link to the heading present in the nav of the projects page.

**Expected behavior**
Must redirect to the parent page/site scodein.tech

**Comment by akanksha-raghav** [comment]
Issue resolved
