### ISSUE TITLE
Fix space of Email in Footer

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#45]
**Screenshots**
![image](https://user-images.githubusercontent.com/48288540/95360398-f02f5200-08e8-11eb-8395-d6568c371c52.png)

**Comment by P3trur0** [comment]
I can take this.

**Comment by lakshyatyagi24** [comment]
Assigned to @P3trur0 

Please start working on it also create more issues if you can.

**Comment by P3trur0** [comment]
Hi there, PR is on its way here.

**Comment by lakshyatyagi24** [comment]
@P3trur0 you fixed this issue only on home page please fix this on all pages

**Comment by kartikagarwal9** [comment]
Assign me, i will do it @lakshyatyagi24

**Comment by lakshyatyagi24** [comment]
Please complete the previously assigned task

**Comment by kartikagarwal9** [comment]
Submitted PR @lakshyatyagi24
