### ISSUE TITLE
Add a pre-loader to website

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#47]
Add a pre-loader to website going with the theme.

**Comment by khushali77** [comment]
Can I take this issue?

**Comment by lakshyatyagi24** [comment]
Sure @khushali77

**Comment by lakshyatyagi24** [comment]
any update? @khushali77

**Comment by vansh1999** [comment]
@lakshyatyagi24 is this issue closed or still need to work on?

**Comment by lakshyatyagi24** [comment]
As there is no update you can work on this

**Comment by akanksha-raghav** [comment]
Any Update @vansh1999

**Comment by AdityaTeltia** [comment]
anyone working on this issue or can I work on it ?

**Comment by lakshyatyagi24** [comment]
@adad20 i think no one is working on it if you want you can work on it

**Comment by AdityaTeltia** [comment]
Sure will do it !
