### ISSUE TITLE
Create a better "Our Sponsor" part

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#49]
Our Sponsors is not looking good improve the css of it and make it better

![image](https://user-images.githubusercontent.com/48288540/95364417-6a160a00-08ee-11eb-8393-0f073d36bbc5.png)

**Comment by Naziya-Parveen** [comment]
I can do it. Please assign me this issue.

**Comment by lakshyatyagi24** [comment]
First let me know your strategy

**Comment by Hsins** [comment]
@lakshyatyagi24 

What would be a good look for that section? Moreover, I found that all the CSS files in this repo are not well-formatted. Would you mind I open an issue for that or just modify and make a pull request with this issue?

**Comment by lakshyatyagi24** [comment]
You can create a new issue for it

**Comment by oneofthedevs** [comment]
Let me see what I can do
