### ISSUE TITLE
Create a Search option in Project Page

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#50]
Create a Search Option to search project by name, tag, keywords or by their technology stack

For Ex:

If i write Flutter in Search bar it will show all the projects based on Flutter Technology Stack

**Comment by TokyoDom** [comment]
Hi I'd like to try this!

**Comment by lakshyatyagi24** [comment]
Sure, 
Fork the repo, Give a Star and Start working on it. Make a pull request then we will check your changes and merge it
