### ISSUE TITLE
Create a new Page for Webinars

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#52]
Instead of sending user to your Youtube channel need to create a new page for it and embedd these videos

**Comment by EANimesha** [comment]
I like to do it. Assign me

**Comment by lakshyatyagi24** [comment]
@EANimesha please refer the link i added below and make the structure similar to [Student Code-In](https://scodein.tech) 
[](https://www.voiceflow.com/events)

**Comment by EANimesha** [comment]
> @EANimesha please refer the link i added below and make the structure similar to [Student Code-In](https://scodein.tech)
> [Voiceflow Events](https://www.voiceflow.com/events)

ok

**Comment by khushali77** [comment]
Is this issue still open? Can I work on this?

**Comment by lakshyatyagi24** [comment]
as there is no update from @EANimesha i think you can also start working on it

**Comment by EANimesha** [comment]
> as there is no update from @EANimesha i think you can also start working on it

I am Working on this. I will send the PR by today
