### ISSUE TITLE
Titles in Timeline Sections are out of borders with browsers in narrow width.

### ISSUE THREAD

**Issue by Hsins** [StudentCode-in/StudentCode-in.github.io#53]
![image](https://user-images.githubusercontent.com/26391143/95373272-5a5aed80-090f-11eb-9608-b34b3aed3baf.png)

**Comment by kartikagarwal9** [comment]
I have solved this issue, I have sent a PR please accept it , in the new code the word doesn't go outside the box whether you see it in any dimensions @lakshyatyagi24

**Comment by lakshyatyagi24** [comment]
@kartikagarwal9 we didn't received your PR please check it and mention pr here

**Comment by kartikagarwal9** [comment]
Sorry just posted yet , slow internet @lakshyatyagi24  . Now it is visible

**Comment by lakshyatyagi24** [comment]
@kartikagarwal9 it's still as it is

**Comment by kartikagarwal9** [comment]
It cannot be possible @lakshyatyagi24 , i checked myself , should I send you screenshot to your mail ?

**Comment by lakshyatyagi24** [comment]
you can attach the screenshot here in comment

**Comment by kartikagarwal9** [comment]
![Screenshot (348)](https://user-images.githubusercontent.com/57009207/95389133-0224eb00-0911-11eb-96ed-2af692deb487.png)
@lakshyatyagi24

**Comment by lakshyatyagi24** [comment]
#55
