### ISSUE TITLE
Team page take more than usual time to load

### ISSUE THREAD

**Issue by akanksha-raghav** [StudentCode-in/StudentCode-in.github.io#58]
Solve the issues of the team page to make it load faster.

**Comment by kartikagarwal9** [comment]
I will try @akanksha-raghav

**Comment by kartikagarwal9** [comment]
I have solved the time lagging in the page and submitted the PR , (Note- I though deleted the image but I have reuploaded it with no changes except image size.)

**Comment by kartikagarwal9** [comment]
I have solved the time lagging in the page and submitted the PR , (Note- I though deleted the image but I have reuploaded it with no changes except image size.)
