### ISSUE TITLE
Search by clicking any tech stack

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#61]
![image](https://user-images.githubusercontent.com/48288540/95437853-23b6be80-0973-11eb-92c0-487856b4ba4d.png)

On clicking any Tech stack it need to show all the projects based on that stack

**Comment by PushpikaWan** [comment]
I would like to take this issue. can you please assign this to me

**Comment by lakshyatyagi24** [comment]
Assigned
