### ISSUE TITLE
Popup is not closing while clicking outside popup

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#68]
Popup is not closing while clicking outside the popup window

![image](https://user-images.githubusercontent.com/48288540/95500877-2215e680-09c5-11eb-9f71-a7fa43644acc.png)

**Comment by andyantunes** [comment]
Hey @lakshyatyagi24 . I would like to work on this problem, could you assign me?

**Comment by lakshyatyagi24** [comment]
sure @andyantunes
