### ISSUE TITLE
Need a search bar in Webinar Page

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#76]
Search for search video by Name, Hashtag, Keyword

**Comment by sarcastic22101** [comment]
hi could you assign this to me? i'd like to try this one :)

**Comment by danielochka** [comment]
Hello, can you tell me more about it? I'm interested in contributing to your project.

**Comment by lakshyatyagi24** [comment]
Need a search bar so that user can search video using name, hashtags of video, specific keywords

**Comment by danielochka** [comment]
Where the search bar should be located?

**Comment by i-dictionary** [comment]
@danielochka top center below header. I think this position is good for it but if you have anything better please go for that

**Comment by danielochka** [comment]
@i-dictionary  okey I can try to do something

**Comment by lakshyatyagi24** [comment]
any update @danielochka ?

**Comment by danielochka** [comment]
@lakshyatyagi24 yup. You ment something like this? I hope you'll get the screenshot.
![second](https://user-images.githubusercontent.com/71976988/96850745-76a27280-1457-11eb-9f0c-66d717966f6c.png)

**Comment by lakshyatyagi24** [comment]
yes

**Comment by danielochka** [comment]
I have another question, where are the videos to search?

**Comment by lakshyatyagi24** [comment]
Videos are available on the same page

**Comment by danielochka** [comment]
After clicking on the stream recording button, the video will open on youtube. The search window currently works in such a way that if I type the name of the video into it, a youtube will be displayed, where the searched video is located at the top. did I understand that correctly? Or can you explain it better?

**Comment by akanksha-raghav** [comment]
Hey, @danielochka sorry for the delay. Can you push the changes you made for a better review?

**Comment by danielochka** [comment]
Hello, @akanksha-raghav  no prob :) . I pushed my changes. Hope I haven't done anything wrong.

**Comment by akanksha-raghav** [comment]
> Hello, @akanksha-raghav no prob :) . I pushed my changes. Hope I haven't done anything wrong.

Great create a pull request with the changes we will review and let you know if changes are required
