### ISSUE TITLE
Deffer Offscreen Images

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#78]
Consider lazy-loading offscreen and hidden images after all critical resources have finished loading to lower time to interactive.

[Source code for Defer offscreen images audit](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/byte-efficiency/offscreen-images.js)

**Comment by inomag** [comment]
Hi there, can I work on this ?

**Comment by lakshyatyagi24** [comment]
Yes you can

**Comment by inomag** [comment]
https://user-images.githubusercontent.com/66073063/103727069-59198980-5000-11eb-9498-be882d329571.mp4


https://user-images.githubusercontent.com/66073063/103727078-5c147a00-5000-11eb-9202-1abd65fb0500.mp4


https://user-images.githubusercontent.com/66073063/103727082-5fa80100-5000-11eb-83ed-1d0ccd9e3e37.mp4

Used Intersection observer for lazy loading. Is it ok?
