### ISSUE TITLE
Design a newsletter

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/StudentCode-in.github.io#82]

**Comment by vansh1999** [comment]
@lakshyatyagi24 Can you specify what needs to be done, i can work on this

**Comment by lakshyatyagi24** [comment]
need a newsletter so that visitors can come and subscribe and we can able to send mail to subscribber

**Comment by vansh1999** [comment]
@lakshyatyagi24 Got it!, one more thing i want to make clear , should i put subscribe button on page or make it pop up , or both

**Comment by lakshyatyagi24** [comment]
just a button on a page is enough

**Comment by vansh1999** [comment]
@lakshyatyagi24 check the PR , added feature to it
