### ISSUE TITLE
Add CSS styling to popup

### ISSUE THREAD

**Issue by akanksha-raghav** [StudentCode-in/StudentCode-in.github.io#87]
Add CSS styling to the registration popup box.
- Change font
- Add styling goes with the theme
- Make popup look attractive.

**Comment by Nitish-web-nik** [comment]
I want to contribute in this issue.

**Comment by akanksha-raghav** [comment]
Sure go ahead @Nitish-web-nik

**Comment by VishakhaAwasthi01** [comment]
can I take this?

**Comment by lakshyatyagi24** [comment]
As there is no update from @Nitish-web-nik . @VishakhaAwasthi01 you can work on this issue

**Comment by VishakhaAwasthi01** [comment]
how do we run this project?

**Comment by lakshyatyagi24** [comment]
@VishakhaAwasthi01 [Student Code-In](https://scodein.tech/) visit this website

**Comment by khushishikhu** [comment]
may i work on this issue

**Comment by akanksha-raghav** [comment]
Sure go ahead @khushishikhu

**Comment by khushishikhu** [comment]
@akanksha-raghav please have a look on the pr

**Comment by blackpandan** [comment]
hello, i want to contribute in this

**Comment by lakshyatyagi24** [comment]
sure @blackpandan

**Comment by Prerna-0202** [comment]
@akanksha-raghav , Thanks for assigning me this issue. I will make pr as soon as possible...
